### ISSUE TITLE
whatcha talkin bout, change width of screen?

### ISSUE THREAD

**Issue by josephholsten** [nwinter/telepath-logger#4]
so I'm getting absolutely no diff from changing `TPWindow.m`'s width to something other than 2560. Nor when I change the (max/min/default) width in `TPHUDWindowController.xib`.

I've somehow managed to get it to resize through a window manager (hammerspoon), but it doesn't resize vertically, scale, whathaveyou. It just cuts off the right side. So I'm not sure what changing the initial width in code is supposed to do.

What behaviour should I be expecting?

**Comment by nwinter** [comment]
Hmm; try also editing the `TPTrackerScreen.m` and `TPWindow.m` files to match the size of your screen as well as doing it in the .xib. (Can you tell I know what I'm doing when it comes to making Mac apps?)

**Comment by josephholsten** [comment]
ah, well it turns out that I had some issue with the build not respecting the updated xib. All's better now!

Now I'm going to learn about how to get these things to resize based on the total width of the bar. then maybe I'll learn about how these trackers work so I can get a skritter, duolingo and habitrpg added.

**Comment by nwinter** [comment]
Awesome–would love to see anything you figure out with respect to making the size less dumb. You can check out the Trello or GitHub trackers for an example of how to pull dashboard-y stats from web services. Here's a commit where I (mostly) add the Trello stuff, so you can see it all together: https://github.com/nwinter/telepath-logger/commit/f2a33511950f17aec4ef107ac38dfe1f76a5033a

**Comment by josephholsten** [comment]
This is my first attempt at any non-web UI stuff, so it'll be slow going. Learning auto-layout constraints now. I mostly want this to look reasonable on my laptop's default 1440px width and still stretch to your impressive 2560px. This will likely take many of my days off.

I'm probably likely to attack extracting all the config stuff into a settings window that can be saved in a plist file. But I'll be sure to support your existing config file locations.

I want to be clear: don't feel obligated to get to anything I post here with any urgency. I know how stressful maintaining open source stuff can be, and code combat is a very impressive community to be organizing. I just think you've got something really useful, and I'd love to help more people be able to use it. Though I'm going to have to deal with my local memory leak before I can expect any normal person to use it.

**Comment by nwinter** [comment]
We can also cut some of the info out; I know I designed it to fit in 2560px and put in a ton of stuff I wanted for my video, but I currently am not using a bunch of it, so if all the extra stuff interferes with making something that more sane resolutions can use, let's figure out a way to make it better for those screens and possibly cut / de-emphasize existing info sections.
