### ISSUE TITLE
QTKit support removed in OSX Sierra

### ISSUE THREAD

**Issue by jeffreybiles** [nwinter/telepath-logger#8]
Do you still use this program?  If you do, how do you get around the issue of QTKit not being available in Sierra or High Sierra?

I'm sure it's a simple fix, but I have not done any Objective-C work.

<img width="1123" alt="screenshot 2017-12-01 18 13 11" src="https://user-images.githubusercontent.com/839123/33508975-6d5639c0-d6c3-11e7-8841-4a3eab1c6d68.png">

**Comment by nwinter** [comment]
Hmm, I'm still using it daily, but I haven't built it in a long time, so haven't looked into that. Possible need to build with an older SDK. Or if you don't need webcam, just rip that code out?

**Comment by jeffreybiles** [comment]
I made it work by building with 10.11 SDK.

![screenshot 2017-12-01 19 34 32](https://user-images.githubusercontent.com/839123/33510180-b7221d70-d6ce-11e7-94a4-bc4204f3fa6a.png)

Now off to get everything else configured.  Thanks for building this, and for helping out tonight!

**Comment by nwinter** [comment]
Awesome! Glad you were able to get it working. Let me know if it satisfies and if you end up doing anything cool with it.
